In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [3]:
df=pd.read_csv(r"C:\Users\AnnamalaiG\OneDrive\Desktop\Coures 9\DS1_C9_S7_Project_AbsenteeismAtWork_Data.csv")

In [5]:
df

ID;Reason for absence;Month of absence;Day of the week;Seasons;Transportation expense;Distance from Residence to Work;Service time;Age;Work load Average/day ;Hit target;Disciplinary failure;Education;Son;Social drinker;Social smoker;Pet;Weight;Height;Body mass index;Absenteeism time in hours
0    11;26;7;3;1;289;36;13;33;239.554;97;0;1;2;1;0;...                                                                                                                                                                                                                                                  
1    36;0;7;3;1;118;13;18;50;239.554;97;1;1;1;1;0;0...                                                                                                                                                                                                                                                  
2    3;23;7;4;1;179;51;18;38;239.554;97;0;1;0;1;0;0...                                                                                                                                                                                                                                                  
3    7;7;7;5;1;279;5;14;39;239.554;97;0;1;2;1;1;0;6...                                                                                                                                                                                                                                                  
4    11;23;7;5;1;289;36;13;33;239.554;97;0;1;2;1;0;...                                                                                                                                                                                                                                                  
..                                                 ...                                                                                                                                                                                                                                                  
735  11;14;7;3;1;289;36;13;33;264.604;93;0;1;2;1;0;...                                                                                                                                                                                                                                                  
736  1;11;7;3;1;235;11;14;37;264.604;93;0;3;1;0;0;1...                                                                                                                                                                                                                                                  
737  4;0;0;3;1;118;14;13;40;271.219;95;0;1;1;1;0;8;...                                                                                                                                                                                                                                                  
738  8;0;0;4;2;231;35;14;39;271.219;95;0;1;2;1;0;2;...                                                                                                                                                                                                                                                  
739  35;0;0;6;3;179;45;14;53;271.219;95;0;1;1;0;0;1...                                                                                                                                                                                                                                                  

[740 rows x 1 columns]

In [7]:
df.columns

Index(['ID;Reason for absence;Month of absence;Day of the week;Seasons;Transportation expense;Distance from Residence to Work;Service time;Age;Work load Average/day ;Hit target;Disciplinary failure;Education;Son;Social drinker;Social smoker;Pet;Weight;Height;Body mass index;Absenteeism time in hours'], dtype='object')

In [9]:
# Task 1
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv(r"C:\Users\AnnamalaiG\OneDrive\Desktop\Coures 9\DS1_C9_S7_Project_AbsenteeismAtWork_Data.csv", delimiter=';')
df = df.fillna(0)
df = pd.get_dummies(df, columns=['Reason for absence'], drop_first=True)
df['High Absenteeism'] = df['Absenteeism time in hours'] > df['Absenteeism time in hours'].median()
features = ['Age', 'Education', 'Son', 'Disciplinary failure', 'Distance from Residence to Work', 'Body mass index'] + [col for col in df.columns if 'Reason for absence' in col]
target = 'High Absenteeism'

X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
log_reg_model = LogisticRegression(max_iter=1000)
log_reg_model.fit(X_train, y_train)
y_pred_log_reg = log_reg_model.predict(X_test)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("Logistic Regression Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg)}")
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

print("\nKNN Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn)}")
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

Logistic Regression Model Evaluation:
Accuracy: 0.8153153153153153
[[100  22]
 [ 19  81]]
              precision    recall  f1-score   support

       False       0.84      0.82      0.83       122
        True       0.79      0.81      0.80       100

    accuracy                           0.82       222
   macro avg       0.81      0.81      0.81       222
weighted avg       0.82      0.82      0.82       222


KNN Model Evaluation:
Accuracy: 0.6981981981981982
[[96 26]
 [41 59]]
              precision    recall  f1-score   support

       False       0.70      0.79      0.74       122
        True       0.69      0.59      0.64       100

    accuracy                           0.70       222
   macro avg       0.70      0.69      0.69       222
weighted avg       0.70      0.70      0.69       222



In [21]:
# Task 2
features = ['Reason for absence', 'Age', 'Disciplinary failure', 'Distance from Residence to Work', 'Body mass index']
target = 'Absenteeism time in hours'
df = pd.get_dummies(df, columns=['Reason for absence'], drop_first=True)
df['High Absenteeism'] = df['Absenteeism time in hours'] > df['Absenteeism time in hours'].median()
features = ['Age', 'Disciplinary failure', 'Distance from Residence to Work', 'Body mass index'] + [col for col in df.columns if 'Reason for absence' in col]
X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
log_reg_model = LogisticRegression(max_iter=1000)
log_reg_model.fit(X_train, y_train)
y_pred_log_reg = log_reg_model.predict(X_test)


knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("Logistic Regression Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg)}")
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

print("\nKNN Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn)}")
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn)

Logistic Regression Model Evaluation:
Accuracy: 0.4774774774774775
[[13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  8 11  2  0  0  5  0  0  0  0  0  0  0]
 [ 0 13 24  9  0  0  5  0  0  0  0  0  0  0]
 [ 0  5 12  6  0  0  9  0  0  0  0  0  0  0]
 [ 0  7  6  3  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  3  3  0  0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.22      0.31      0.25        26
           2       0.42      0.47      0.44        51
           3       0.30      0.19      0.23        32
           4       0.00      0.

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels wi